version: '3.2'
services:
  terraform:
    container_name: terraform
    image: hashicorp/terraform:0.13.4
    network_mode: host
    volumes:
      - type: bind
        source: "${PWD}"
        target: /tf
    working_dir: /tf
